import os
import json

def generate_system_metrics_report(chunk_metrics, embed_metrics, db_metrics, llm_metrics, perf_metrics, output_path="reports/system_metrics.md"):
    """
    Generates the mandatory system metrics report in Markdown format.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    report = f"""# System Metrics Report

## Chunking Profile
* **Chunk strategy**: Fixed-size sliding window
* **Chunk size**: {chunk_metrics.get('chunk_size')} characters
* **Overlap**: {chunk_metrics.get('chunk_overlap')} characters
* **Number of chunks**: {chunk_metrics.get('total_chunks')}
* **Average chunk length**: {chunk_metrics.get('average_chunk_length'):.1f} characters

## Embedding Configuration
* **Model name**: {embed_metrics.get('model_name')}
* **Embedding dimensions**: {embed_metrics.get('dimension')}

## Vector Database
* **Database type**: {db_metrics.get('type', 'FAISS')}
* **Similarity metric**: {db_metrics.get('metric', 'L2 Distance')}
* **Top-k value**: {db_metrics.get('top_k', 5)}

## Language Model
* **Model name**: {llm_metrics.get('model_name')}
* **Temperature**: {llm_metrics.get('temperature')}
* **Context window limit**: Varies by model (typical 8k-128k)

## Performance Metrics
* **Chunking Time**: {chunk_metrics.get('processing_time_sec')} seconds
* **Ingestion Time (Total)**: {perf_metrics.get('ingestion_time', 0):.4f} seconds
* **Average Retrieval Latency**: {perf_metrics.get('avg_retrieval_latency', 0):.4f} seconds
* **Average Generation Latency**: {perf_metrics.get('avg_generation_latency', 0):.4f} seconds
* **Average End-to-End Latency**: {perf_metrics.get('avg_e2e_latency', 0):.4f} seconds

---
*Generated by RAG Evaluation Pipeline.*
"""
    with open(output_path, "w") as f:
        f.write(report)
        
    print(f"System metrics report generated at {output_path}")
